name: Flex Plugins CLI - Jailbrake E2E Nightly

on:
  schedule:
    - cron: '0 7 * * *' # At 7:00 UTC (12:30 IST) every day
    - cron: '0 8 * * *' # At 8:00 UTC (13:30 IST) every day
    - cron: '0 9 * * *' # At 9:00 UTC (14:30 IST) every day

jobs:
  scheduled-e2e-unix-jailbreak:
    if: github.event.schedule == '0 7 * * *'
    uses: ./.github/workflows/~reusable_e2e_by_OS.yaml
    with:
      OS: ubuntu-22.04
      BRANCH: main
      NPM_IGNORE_PREFIX: ${{ vars.NPM_IGNORE_PREFIX }}
      PACKAGE_VERSION: latest
      FLEX_UI_VERSION: latest
      SLACK_TITLE: 'Flex Plugins CLI - E2E Nightly for Jailbrea'
      SEND_NOTIFICATION: true
    secrets:
      CONSOLE_EMAIL: ${{ secrets.CONSOLE_EMAIL }}
      CONSOLE_PASSWORD: ${{ secrets.CONSOLE_PASSWORD }}
      SLACK_WEB_HOOK: ${{ secrets.SLACK_WEB_HOOK }}
      CONSOLE_EMAIL_linux_jailbreak: ${{ secrets.CONSOLE_EMAIL_linux_jailbreak }}
      TWILIO_ACCOUNT_SID_linux_jailbreak: ${{ secrets.TWILIO_ACCOUNT_SID_linux_jailbreak }}
      TWILIO_AUTH_TOKEN_linux_jailbreak: ${{ secrets.TWILIO_AUTH_TOKEN_linux_jailbreak }}
      CONSOLE_EMAIL_win32_jailbreak: ${{ secrets.CONSOLE_EMAIL_win32_jailbreak }}
      TWILIO_ACCOUNT_SID_win32_jailbreak: ${{ secrets.TWILIO_ACCOUNT_SID_win32_jailbreak }}
      TWILIO_AUTH_TOKEN_win32_jailbreak: ${{ secrets.TWILIO_AUTH_TOKEN_win32_jailbreak }}
      CONSOLE_EMAIL_darwin_jailbreak: ${{ secrets.CONSOLE_EMAIL_darwin_jailbreak }}
      TWILIO_ACCOUNT_SID_darwin_jailbreak: ${{ secrets.TWILIO_ACCOUNT_SID_darwin_jailbreak }}
      TWILIO_AUTH_TOKEN_darwin_jailbreak: ${{ secrets.TWILIO_AUTH_TOKEN_darwin_jailbreak }}

  scheduled-e2e-macos-jailbreak:
    if: github.event.schedule == '0 8 * * *'
    uses: ./.github/workflows/~reusable_e2e_by_OS.yaml
    with:
      OS: macos-latest
      BRANCH: main
      NPM_IGNORE_PREFIX: ${{ vars.NPM_IGNORE_PREFIX }}
      PACKAGE_VERSION: latest
      FLEX_UI_VERSION: latest
      SLACK_TITLE: 'Flex Plugins CLI - E2E Nightly for Jailbreak'
      SEND_NOTIFICATION: true
    secrets:
      CONSOLE_EMAIL: ${{ secrets.CONSOLE_EMAIL }}
      CONSOLE_PASSWORD: ${{ secrets.CONSOLE_PASSWORD }}
      SLACK_WEB_HOOK: ${{ secrets.SLACK_WEB_HOOK }}
      CONSOLE_EMAIL_linux_jailbreak: ${{ secrets.CONSOLE_EMAIL_linux_jailbreak }}
      TWILIO_ACCOUNT_SID_linux_jailbreak: ${{ secrets.TWILIO_ACCOUNT_SID_linux_jailbreak }}
      TWILIO_AUTH_TOKEN_linux_jailbreak: ${{ secrets.TWILIO_AUTH_TOKEN_linux_jailbreak }}
      CONSOLE_EMAIL_win32_jailbreak: ${{ secrets.CONSOLE_EMAIL_win32_jailbreak }}
      TWILIO_ACCOUNT_SID_win32_jailbreak: ${{ secrets.TWILIO_ACCOUNT_SID_win32_jailbreak }}
      TWILIO_AUTH_TOKEN_win32_jailbreak: ${{ secrets.TWILIO_AUTH_TOKEN_win32_jailbreak }}
      CONSOLE_EMAIL_darwin_jailbreak: ${{ secrets.CONSOLE_EMAIL_darwin_jailbreak }}
      TWILIO_ACCOUNT_SID_darwin_jailbreak: ${{ secrets.TWILIO_ACCOUNT_SID_darwin_jailbreak }}
      TWILIO_AUTH_TOKEN_darwin_jailbreak: ${{ secrets.TWILIO_AUTH_TOKEN_darwin_jailbreak }}

  scheduled-e2e-windows-jailbreak:
    if: github.event.schedule == '0 9 * * *'
    uses: ./.github/workflows/~reusable_e2e_by_OS.yaml
    with:
      OS: windows-latest
      BRANCH: main
      NPM_IGNORE_PREFIX: ${{ vars.NPM_IGNORE_PREFIX }}
      PACKAGE_VERSION: latest
      FLEX_UI_VERSION: latest
      SLACK_TITLE: 'Flex Plugins CLI - E2E Nightly for Jailbreak'
      SEND_NOTIFICATION: true
    secrets:
      CONSOLE_EMAIL: ${{ secrets.CONSOLE_EMAIL }}
      CONSOLE_PASSWORD: ${{ secrets.CONSOLE_PASSWORD }}
      SLACK_WEB_HOOK: ${{ secrets.SLACK_WEB_HOOK }}
      CONSOLE_EMAIL_linux_jailbreak: ${{ secrets.CONSOLE_EMAIL_linux_jailbreak }}
      TWILIO_ACCOUNT_SID_linux_jailbreak: ${{ secrets.TWILIO_ACCOUNT_SID_linux_jailbreak }}
      TWILIO_AUTH_TOKEN_linux_jailbreak: ${{ secrets.TWILIO_AUTH_TOKEN_linux_jailbreak }}
      CONSOLE_EMAIL_win32_jailbreak: ${{ secrets.CONSOLE_EMAIL_win32_jailbreak }}
      TWILIO_ACCOUNT_SID_win32_jailbreak: ${{ secrets.TWILIO_ACCOUNT_SID_win32_jailbreak }}
      TWILIO_AUTH_TOKEN_win32_jailbreak: ${{ secrets.TWILIO_AUTH_TOKEN_win32_jailbreak }}
      CONSOLE_EMAIL_darwin_jailbreak: ${{ secrets.CONSOLE_EMAIL_darwin_jailbreak }}
      TWILIO_ACCOUNT_SID_darwin_jailbreak: ${{ secrets.TWILIO_ACCOUNT_SID_darwin_jailbreak }}
      TWILIO_AUTH_TOKEN_darwin_jailbreak: ${{ secrets.TWILIO_AUTH_TOKEN_darwin_jailbreak }}