name: Manual Alpha Release with E2E

on:
  workflow_dispatch:
    inputs:
      branch:
        type: string
        description: The Branch to build
        required: true

jobs:
  get-version:
    - name: Retrieve Alpha Patch Version
      run: |
        currentVersion=$(awk '/version/{gsub(/("|",)/,"",$2);print $2}' lerna.json)
        semver=( ${currentVersion//./ } )
        echo "version=${semver[0]}.${semver[1]}.$((semver[2] + 1))-alpha.$(date '+%Y%m%d%H%M')" >> "$GITHUB_OUTPUT"
  release-alpha-version:
    needs: get-version
    uses: ./.github/workflows/reusable_publish.yaml
    with:
      TAG: alpha
      VERSION: ${{needs.get-version.outputs.version}}
      BRANCH: ${{ github.event.inputs.branch }}
      ENVIRONMENT: alpha_release
    secrets:
      NODE_AUTH_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}
      SLACK_WEBHOOK: ${{ secrets.SLACK_WEB_HOOK }}

  e2e-test:
    needs: [ get-version, release-alpha-version ]
    uses: ./.github/workflows/reusable_e2e.yaml
    with:
      BRANCH: ${{ github.event.inputs.branch }}
      NPM_IGNORE_PREFIX: ${{ vars.NPM_IGNORE_PREFIX }}
      PACKAGE_VERSION: ${{needs.get-version.outputs.version}}
      FLEX_UI_VERSION: latest
    secrets:
      CONSOLE_EMAIL: ${{ secrets.CONSOLE_EMAIL }}
      CONSOLE_PASSWORD: ${{ secrets.CONSOLE_PASSWORD }}
      CONSOLE_EMAIL_linux: ${{ secrets.CONSOLE_EMAIL_linux }}
      TWILIO_ACCOUNT_SID_linux: ${{ secrets.TWILIO_ACCOUNT_SID_linux }}
      TWILIO_AUTH_TOKEN_linux: ${{ secrets.TWILIO_AUTH_TOKEN_linux }}
      CONSOLE_EMAIL_win32: ${{ secrets.CONSOLE_EMAIL_win32 }}
      TWILIO_ACCOUNT_SID_win32: ${{ secrets.TWILIO_ACCOUNT_SID_win32 }}
      TWILIO_AUTH_TOKEN_win32: ${{ secrets.TWILIO_AUTH_TOKEN_win32 }}
      CONSOLE_EMAIL_darwin: ${{ secrets.CONSOLE_EMAIL_darwin }}
      TWILIO_ACCOUNT_SID_darwin: ${{ secrets.TWILIO_ACCOUNT_SID_darwin }}
      TWILIO_AUTH_TOKEN_darwin: ${{ secrets.TWILIO_AUTH_TOKEN_darwin }}