name: Manual Public Release v6

on:
  workflow_dispatch:
    inputs:
      version:
        type: choice
        description: The Version type for PUBLIC Release
        options:
          - patch
          - minor
          - major
        required: true

jobs:
  release-public-version:
    if: github.ref == 'refs/heads/main'
    uses: ./.github/workflows/~reusable_public_publish.yaml
    with:
      TAG: public
      VERSION: patch
      BRANCH: FLEXY-5323-6.4.2
      ENVIRONMENT: public_release
    secrets:
      NODE_AUTH_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}
      SLACK_WEB_HOOK: ${{ secrets.SLACK_WEB_HOOK }}
      G_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      APP_ID: ${{ secrets.APP_ID }}
      APP_KEY: ${{ secrets.APP_KEY }}

  release-tag:
    if: github.ref == 'refs/heads/main'
    needs: release-public-version
    uses: ./.github/workflows/tag.yaml

  e2e-node:
    if: github.ref == 'refs/heads/main'
    uses: ./.github/workflows/~reusable_e2e_all_OS.yaml
    needs: release-tag
    with:
      BRANCH: FLEXY-5323-6.4.2
      NPM_IGNORE_PREFIX: ${{ vars.NPM_IGNORE_PREFIX }}
      PACKAGE_VERSION: 6.4.2
      FLEX_UI_VERSION: latest
      SEND_NOTIFICATION: true
      SLACK_TITLE: 'Public Manual Release v6 E2E for Version ${{ github.event.inputs.version }}'
      SLACK_MESSAGE: 'Release E2E'
    secrets:
      CONSOLE_EMAIL: ${{ secrets.CONSOLE_EMAIL }}
      CONSOLE_PASSWORD: ${{ secrets.CONSOLE_PASSWORD }}
      CONSOLE_EMAIL_linux: ${{ secrets.CONSOLE_EMAIL_linux }}
      TWILIO_ACCOUNT_SID_linux: ${{ secrets.TWILIO_ACCOUNT_SID_linux }}
      TWILIO_AUTH_TOKEN_linux: ${{ secrets.TWILIO_AUTH_TOKEN_linux }}
      CONSOLE_EMAIL_win32: ${{ secrets.CONSOLE_EMAIL_win32 }}
      TWILIO_ACCOUNT_SID_win32: ${{ secrets.TWILIO_ACCOUNT_SID_win32 }}
      TWILIO_AUTH_TOKEN_win32: ${{ secrets.TWILIO_AUTH_TOKEN_win32 }}
      CONSOLE_EMAIL_darwin: ${{ secrets.CONSOLE_EMAIL_darwin }}
      TWILIO_ACCOUNT_SID_darwin: ${{ secrets.TWILIO_ACCOUNT_SID_darwin }}
      TWILIO_AUTH_TOKEN_darwin: ${{ secrets.TWILIO_AUTH_TOKEN_darwin }}
      SLACK_WEB_HOOK: ${{ secrets.SLACK_WEB_HOOK }}
