name: PR validator

on:
  pull_request:
    branches:
      - main

  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Install project dependencies
        run: npm i
      - name: Apt-get update
        run: sudo apt-get update
      - name: Install libraries
        run: sudo apt-get install -y libsecret-1-dev
      - name: Run linter
        run: npm run lint:fix
      - name: Build packages
        run: npm run build
      - name: Codecov report
        run: npm run coverage -- --token=$CODECOV_TOKEN
        
      



  