name: PR Validator - Build and Test

on:
  pull_request:
    branches:
      - main
    paths-ignore:
      - 'lerna.json'
      - '**/package-lock.json'
      - '**/package.json'
  push:
    branches:
      - main
    paths-ignore:
      - 'lerna.json'
      - '**/package-lock.json'
      - '**/package.json'

env:
  ARTIFACTORY_URL: ${{ vars.ARTIFACTORY_URL }}

jobs:
  build-and-test:
    runs-on: ubuntu-x64
    permissions:
      id-token: write # Required for Artifactory OIDC
      contents: read
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
      - name: Authenticate to Artifactory (OIDC)
        uses: ./.github/actions/artifactory-oidc
      - uses: actions/setup-node@3235b876344d2a9aa001b8d1453c930bba69e610 # v3
        with:
          node-version: '22'

      - name: Install project dependencies
        run: npm ci --verbose
      - name: Run linter
        run: npm run lint:fix
      - name: Run Tests
        run: npm run test:ci
        env:
          TWILIO_ACCOUNT_SID: ${{ secrets.TWILIO_ACCOUNT_SID_linux }}
          TWILIO_AUTH_TOKEN: ${{ secrets.TWILIO_AUTH_TOKEN_linux }}
          NODE_OPTIONS: --no-experimental-fetch
          CI: ""
      - name: Build packages
        run: npm run build
      # - name: Codecov report
      #   uses: codecov/codecov-action@ab904c41d6ece82784817410c45d8b8c02684457 # v3
      #   with:
      #     token: ${{ secrets.CODECOV_TOKEN }}

  