name: Publish on merge to dev

on:
  pull_request:
    types: [closed]
    branches:
      - dev

job:
  trigger-npm-publish:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged

    steps:
      - name: Trigger NPM Publish job via CURL
        env:
          CIRCLECI_TOKEN: ${{ secrets.CIRCLECI_TOKEN }}
        run: |
          curl -u "${CIRCLECI_TOKEN}:" -X POST -H "Content-Type: application/json" \
          -d "{\"parameters\":{\"run_e2e_test\":false, \"run_pr_validator\":false, \"dist_tag\":\"dev\"}, \"version_bump\":\"patch\"}, \"branch\":\"dev\"}" \
          https://circleci.com/api/v2/project/github/twilio/flex-plugin-builder/pipeline