on:
  workflow_call:

jobs:
  node:
    strategy:
      matrix:
        os: [ubuntu-22.04, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - run: echo "e2e not required. Passing status check"
