on:
  workflow_call:

jobs:
  node:
    strategy:
      matrix:
        os: [ubuntu-latest-large, windows-latest-large, macos-latest-large]
    runs-on: ${{ matrix.os }}
    steps:
      - run: echo "e2e not required. Passing status check"
